#! /bin/sh

setxkbmap -layout es

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bash ~/.config/polybar/launch.sh &

nitrogen --restore

light-locker &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Pavucontrol state=floating rectangle=1000x700+2600+100
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
